name: 'Publish Klayr Core'

on:
  push:
    tags:
      - 'v*'

jobs:
  code-cov-canary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install
        uses: ./.github/actions/prepare-install
      - run: yarn build
      - run: yarn lint
      - run: yarn format
      - run: yarn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage-final.json
          name: codecov-umbrella
      - run: npm config set //npm.klayr.dev/:_authToken=$NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        run: npx lerna publish --registry https://npm.klayr.dev --yes
